{% set version = '0.0.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-procmaps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/procmaps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/procmaps/procmaps_{{ version }}.tar.gz
  sha256: c92c59e48107fc64d175840a2e408c7d9e6e608cde1a0568db490b92825fac30

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'   # [win]

requirements:
  build:
    - {{ stdlib("c") }}  # [not win]
    - {{ stdlib("m2w64_c") }}  # [win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('procmaps')"           # [not win]
    - "\"%R%\" -e \"library('procmaps')\""  # [win]

about:
  home: https://r-prof.github.io/procmaps/
  dev_url: https://github.com/r-prof/procmaps
  license: GPL-3.0-only
  summary: Portable '/proc/self/maps' as a data frame. Determine which library or other region
    is mapped to a specific address of a process. -- R packages can contain native code,
    compiled to shared libraries at build or installation time. When loaded, each shared
    library occupies a portion of the address space of the main process. When only a
    machine instruction pointer is available (e.g. from a backtrace during error inspection
    or profiling), the address space map determines which library this instruction pointer
    corresponds to.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: procmaps
# Title: Portable Address Space Mapping
# Version: 0.0.5
# Date: 2023-01-19
# Authors@R: c(person(given = "Kirill", family = "M\u00fcller", role = c("aut", "cre"), email = "kirill@cynkra.com", comment = c(ORCID = "0000-0002-1416-3412")), person(given = "R Consortium", role = "fnd"), person(given = "Kostya", family = "Serebryany", role = "ctb", comment = "Bundled gperftools library"), person(given = "Sanjay", family = "Ghemawat", role = "ctb", comment = "Bundled gperftools library"), person(given = "Craig", family = "Silverstein", role = "ctb", comment = "Bundled gperftools library"), person(family = "Google Inc.", role = "cph", comment = "Bundled gperftools library"))
# Description: Portable '/proc/self/maps' as a data frame. Determine which library or other region is mapped to a specific address of a process. -- R packages can contain native code, compiled to shared libraries at build or installation time. When loaded, each shared library occupies a portion of the address space of the main process. When only a machine instruction pointer is available (e.g. from a backtrace during error inspection or profiling), the address space map determines which library this instruction pointer corresponds to.
# License: GPL-3
# URL: https://r-prof.github.io/procmaps/, https://github.com/r-prof/procmaps
# BugReports: https://github.com/r-prof/procmaps/issues
# Suggests: covr, testthat, tibble
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# NeedsCompilation: yes
# Packaged: 2023-01-19 20:11:56 UTC; kirill
# Author: Kirill Muller [aut, cre] (<https://orcid.org/0000-0002-1416-3412>), R Consortium [fnd], Kostya Serebryany [ctb] (Bundled gperftools library), Sanjay Ghemawat [ctb] (Bundled gperftools library), Craig Silverstein [ctb] (Bundled gperftools library), Google Inc. [cph] (Bundled gperftools library)
# Maintainer: Kirill Muller <kirill@cynkra.com>
# Repository: CRAN
# Date/Publication: 2023-01-20 17:10:02 UTC
